version: '3.4'

services:
  hello.console:
    container_name: hello-console
    image: ${DOCKER_REGISTRY-}hello.console
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hello.redis

  hello.redis:
    container_name: hello-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - $HOME/redis/net-hello/d–∞ta:/root/redis
      - $HOME/redis/net-hello/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      #- REDIS_PASSWORD=123
      #- REDIS_DATABASES=16