# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY . .

# RUN dotnet restore
RUN dotnet restore "HelloApp.csproj" --disable-parallel

RUN dotnet publish "HelloApp.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "HelloApp.dll"]